### ISSUE TITLE
Works great.. except for Readwise pages

### ISSUE THREAD

**Issue by zendude213** [stevenrombauts/alfred-workflow-notion#1]
Hey Steven

Thanks for creating this.. It was working well and was displaying the results properly until I decided to import my book highlights through Readwise's Notion integration... In this context, searches for readwise book titles would return what seems to be a unique identifier (see pix below). It's not just readwise, but I think 98% of it are

![Screen-Shot-2021-12-29-02-10-51](https://user-images.githubusercontent.com/59263556/147636738-d91b8c0a-6b87-4731-852a-7831396f8c3e.png)
)

**Comment by stevenrombauts** [comment]
Hi @zendude213, thanks for the report. Determining Page titles in Notion can be a tricky thing. I discovered some Pages in my own Notion library that were incorrectly shown as well. 

I've fixed these and uploaded a new version at https://github.com/stevenrombauts/alfred-workflow-notion/releases/tag/v1.0.1 - let me know if that solves your problem too.
